# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 021951901fb38a60ae2440881115c87dfffb79aa1a1babe0545f601f2897e336ebc9bb8d9379825e36d610d28689bfa64970d93f4ead8e7994c973e1ad9aacb5

test:
  secret_key_base: b4bdf1b0ba1cbb8e38fbf5a9ff5594b84599d51f11aa9fdac107ac7a799b8f264f7da5bd963fb93e403c731172ddbb2fbfe223afbdfbdf463fc45331b3784d34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
